Fix/header/usercard width
su-its/typing pull request #107
Opened 2024-04-06 16:40 UTC by KikyoNanakusa

## チケットへのリンク
resolve https://github.com/su-its/typing/issues/101
## やったこと
UserCardの幅を固定
## やらないこと
なし
## できるようになること（ユーザ目線）
長いユーザー名を使ってもスタイルが崩れなくなる 
## 動作確認
ローカルで確認

2024-04-06 22:53 UTC, KinjiKawaguchi requested changes

2024-04-06 22:53 UTC, KinjiKawaguchi commented on typing-app/src/components/molecules/UserCard.tsx
> +          名前: {user ? user.handleName : "ログインしていませんaaaaaaaaa"}
```suggestion
          名前: {user ? user.handleName : "ログインしていません"}
```

2024-04-06 22:53 UTC, KinjiKawaguchi commented
デモ文章にも、「うんこ」とかは使うなと同じ

2024-04-07 04:41 UTC, h-takeyeah commented
幅は設定できているのですが画面右端に空白ができてしまうので https://web-camp.io/magazine/archives/90660 などを見ながら直してみています

2024-04-07 05:57 UTC, h-takeyeah commented
Chakra UI で isTruncated を使うとあふれたら`...`表記になるために必要な CSS プロパティをよしなに設定してくれる。その中の一つ `text-overflow: ellipsis;` を flex コンテナ内で正しく効かせるためには追加で親要素にも `overflow: hidden;` を設定する必要があることがわかった。その対応をしたら下記画像の通り直って、謎の空白も消えた。空白があったというのは、見た目上は青いボックスで UserCard が切れているのだが、あふれた部分が見えないけど存在してることになって、それが余計な空白をページ右端に生んでいた、ということ。これによって横スクロールバーが表示されており、少し汚かった。

![image](https://github.com/su-its/typing/assets/61489178/87cce131-34cd-4776-9fa9-cb36b1c26123)

2024-04-07 06:13 UTC, h-takeyeah approved these changes

2024-04-07 11:38 UTC, KikyoNanakusa commented on typing-app/src/components/molecules/UserCard.tsx
> +          名前: {user ? user.handleName : "ログインしていませんaaaaaaaaa"}
誤プッシュにごわす
すいません

2024-04-07 12:55 UTC, merged