Fix/game screen/typing
su-its/typing pull request #120
Opened 2024-04-10 05:29 UTC by Tsuyopon-1067

## チケットへのリンク

- https://github.com/su-its/typing/issues/76

## やったこと

- 打ち出しの反応不良を修正
- 文中での入力できない文字の修正

## やらないこと

- 無し

## できるようになること（ユーザ目線）

- 入力バグが減る

## できなくなること（ユーザ目線）

- 無し

## 動作確認

- yarn buildできることを確認
```[bash]
% yarn build
yarn run v1.22.19
$ next build
   ▲ Next.js 14.1.0
   - Environments: .env

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types    
 ✓ Collecting page data    
 ✓ Generating static pages (7/7) 
 ✓ Collecting build traces    
 ✓ Finalizing page optimization    

Route (app)                              Size     First Load JS
┌ ○ /                                    1.57 kB         258 kB
├ ○ /_not-found                          885 B          85.2 kB
├ ○ /game                                9.56 kB         139 kB
└ ○ /ranking                             1.67 kB         136 kB
+ First Load JS shared by all            84.3 kB
  ├ chunks/69-684208d8427a30a4.js        28.9 kB
  ├ chunks/fd9d1056-780053702ed842a5.js  53.4 kB
  └ other shared chunks (total)          2.04 kB

○  (Static)  prerendered as static content

✨  Done in 13.70s.
```

## その他

- レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

2024-04-10 06:38 UTC, h-takeyeah commented
スコアを登録するところは素のfetchではなく`@/libs/api`から`client`をimportし、それを使って実装するようにしてください

2024-04-10 11:04 UTC, Tsuyopon-1067 commented
七草くんがすでにclientを使うように変更してくれていた（もうマージされているらしい）ので，マージのときにfetch部分を消していただきたいです

2024-04-14 08:54 UTC, h-takeyeah requested changes
api と db を docker コンテナとして立てたうえで、 yarn dev して <http://localhost:3000/game> にアクセスしての動作確認はしました
なのでこの PR で何かデグレってることはたぶんなくて、対数関数グラフが適切に線形のグラフに変わったし、develop ブランチから遅れていた内容も直ってると思います

**気になりポイント**

そこはOKなんですが、一方で<http://localhost:3000> からログインの手順を踏んで game に移動しようとすると、うまくいきませんでした

また、別件でコンソールに画像のような警告が出ているので、もし対応できたら対応おお願いします(この PR でなくてもよいですが)
![image](https://github.com/su-its/typing/assets/61489178/b06c76e4-792d-42b9-9404-38d3ae75ff4a)

2024-04-14 08:54 UTC, h-takeyeah commented on typing-app/src/components/templates/GameTyping.tsx
`getCurrentUser` を2回 import してるのを修正してくださいー(は Discord で伝えたとおりですが)

あと `currentTypeSpeed` はリアクティブな値になってるけど誰も使ってないみたいです、消してもよきなのかしら？ちょっとわかりません

2024-04-14 12:16 UTC, KinjiKawaguchi submitted a review, later dismissed

2024-04-16 04:01 UTC, Tsuyopon-1067 commented on typing-app/src/components/templates/GameTyping.tsx
getCurrentUserの2回importは他の人が直してくれたっぽいですかね…？
currentTypeSpeedは今のUIでは瞬間タイピング速度のゲージが無いので使われていないですがUIが対応されたら使われるはずです（どうなるかは謎）
今はコメントアウトで対処したほうが良きでしょうか？

2024-04-16 10:37 UTC, h-takeyeah submitted a review, later dismissed
GameTyping.tsx のゲージのところに瞬間タイピング速度を復活させるかどうか決めたらあとはOKです

2024-04-16 13:06 UTC, h-takeyeah commented on typing-app/src/components/templates/GameTyping.tsx
> currentTypeSpeedは今のUIでは瞬間タイピング速度のゲージが無いので使われていないですがUIが対応されたら使われるはずです（どうなるかは謎） 

どうなるかは謎でしたが、かわきんくんと話して今のところ消したままでという対応になったので Tsuyopon には申し訳ないけれど使わない部分なので瞬間タイピング速度の部分消させてもらいました。

https://github.com/su-its/typing/pull/120/commits/d4a7383419c4c28483fad483be8b03b9223b4cca

2024-04-16 13:07 UTC, h-takeyeah commented
瞬間タイピング速度の件は結局消すことにした 詳細→ https://github.com/su-its/typing/pull/120#discussion_r1567329208

2024-04-16 13:07 UTC, h-takeyeah approved these changes

2024-04-16 13:08 UTC, merged

2024-04-16 13:08 UTC, h-takeyeah commented
お疲れさまでした