Feat/frontend/frame
su-its/typing pull request #14
Opened 2024-03-16 10:28 UTC by KinjiKawaguchi

## やったこと
フロントエンド開発ように、フレームレイアウトを作成(雑)

2024-03-16 12:06 UTC, h-takeyeah requested changes
みました

ビルドしたときに警告が出てるので対応お願いします:bow:

https://github.com/su-its/typing/actions/runs/8307123255/job/22735984165#step:4:18

別件で、このブランチで `bun i` で依存関係をインストールしたら `bun.lockb`が書き換わってしまったのですが、何か間違えましたかね…？(心当たりがない)

2024-03-16 12:20 UTC, KinjiKawaguchi commented on typing-app/src/components/atoms/Banner.tsx
> +      <Image src={bannerImage.src} alt="Logo" maxH={100} />
ライトモードは目の敵なのでその方向で行きたいと思います。
ありがとうございます。

2024-03-16 13:01 UTC, h-takeyeah commented on typing-app/src/components/organism/Header.tsx
> +import Separator from "../atoms/Separater";
統一
```suggestion
import Separator from "@/components/atoms/Separater";
```

2024-03-17 06:55 UTC, h-takeyeah approved these changes
:ok_man: お疲れ様でした！マージは任せます

2024-03-17 06:57 UTC, merged