Feat/home screen/buttons
su-its/typing pull request #18
Opened 2024-03-23 08:49 UTC by KikyoNanakusa

## チケットへのリンク
https://github.com/orgs/su-its/projects/1/views/1?pane=issue&itemId=57422910

## やったこと
ホームページにボタンを配置
各ページへの遷移を実装
## やらないこと
ログアウト時の処理の実装

## できるようになること（ユーザ目線）
ホームページの表示
## できなくなること（ユーザ目線）
なし
## 動作確認
ブラウザで確認
## その他
フロント不慣れなので気になるところがあれば厳しめにお願いします
サーバーサイドコンポーネントだとAppRouter使えないって言われたので`use client`しちゃってるんですけどこれはいいんでしょうか
![2024-03-23 17 44 52 localhost d393481aa919](https://github.com/su-its/typing/assets/65284574/133c017b-ec7d-4509-8e13-dc23981becbf)

2024-03-24 13:09 UTC, h-takeyeah commented
@KikyoNanakusa prettier でコードをフォーマットしてコミットしてほしいです。本当はpush時にCIでフォーマッタが走るべきなんだけど、整備してなくてすみません。`npx prettier . --write`

2024-03-24 13:17 UTC, KikyoNanakusa commented
@h-takeyeah これで適用できてますかね

2024-03-24 13:35 UTC, h-takeyeah commented
@KikyoNanakusa できてます！

2024-03-24 15:22 UTC, KinjiKawaguchi requested changes
- GameStartButtonなどのボタンは汎用的なコンポーネントじゃないのてmoleculesに分類すべき

この記事が非常に良かった
https://note.com/tabelog_frontend/n/n4b8bcb44294c


- loginページを作る必要は無いと思っていて、homeページで状態管理で学籍番号の入力フォームを表示するぐらいで良さそう

2024-03-24 15:22 UTC, KinjiKawaguchi commented on typing-app/src/components/organism/HomeMenuContainer.tsx
> +// components/MenuContainer.js
```suggestion
```

2024-03-24 15:22 UTC, KinjiKawaguchi commented on typing-app/src/components/atoms/RankingButton.tsx
> +// components/buttons/RankingButton.js
```suggestion
```

2024-03-24 15:22 UTC, KinjiKawaguchi commented on typing-app/src/components/atoms/LogoutButton.tsx
> +// components/buttons/LogoutButton.js
```suggestion
```

2024-03-24 15:22 UTC, KinjiKawaguchi commented on typing-app/src/components/atoms/GameStartButton.tsx
> +// components/buttons/GameStartButton.js
```suggestion
```

2024-03-24 15:24 UTC, KinjiKawaguchi commented
や、loginページの有無に関しては任せます。

2024-03-24 15:29 UTC, KinjiKawaguchi requested changes

2024-03-24 15:29 UTC, KinjiKawaguchi commented on typing-app/src/components/atoms/GameStartButton.tsx
> +    </Button>
hrefでの遷移と、useRouterでの遷移が混在しています。

href↓
リンクとしての意味合いが強く、ページ全体がリロードされます。
ブラウザの戻る/進むボタンでナビゲーションができます。
外部リンクへの遷移に適しています。

useRouterのpush↓
JavaScriptによるプログラム制御の意味合いが強く、ページのリロードは発生しません。
シングルページアプリケーション（SPA）での遷移に適しています。
ブラウザの戻る/進むボタンでナビゲーションができます（適切な設定が必要）。
動的なURLパラメータを渡すことができます。

2024-03-25 00:48 UTC, h-takeyeah commented
HomeMenuContainerという名前からはMenuという単語があることから、私はmoreculeみを感じるんですけどorganismなんですかね。変更しろって意味ではなくてどうなんだろうかっていう。あとログインページは pagesで完結してるけどホームの方はorganismを呼び出していてpageだけでは完結してないという違いがあるけど、これは意図的？

2024-03-26 10:50 UTC, KikyoNanakusa commented on typing-app/src/components/atoms/GameStartButton.tsx
> +    </Button>
useRouterに統一しました

2024-03-26 11:03 UTC, KikyoNanakusa commented
> HomeMenuContainerという名前からはMenuという単語があることから、私はmoreculeみを感じるんですけどorganismなんですかね。変更しろって意味ではなくてどうなんだろうかっていう。あとログインページは pagesで完結してるけどホームの方はorganismを呼び出していてpageだけでは完結してないという違いがあるけど、これは意図的？

HomeMenuContainerはボタンを組み合わせた一つのUIの単位として作ったつもりなのでorganismに置いたんですがどうなんでしょう。いかんせんAtomic Designに疎く.... どちらかというと命名の問題な気もする

LoginPageは廃止してモーダルにしました。

2024-03-26 11:51 UTC, h-takeyeah commented
なるほどー！Atomic Design 何も分からないので、これ以上はやめておきます！

2024-03-27 02:10 UTC, KinjiKawaguchi commented on typing-app/src/components/molecules/LogoutButton.tsx
> +    router.push("/"); //リダイレクト
これは何の為に置いてありますか?

2024-03-27 02:20 UTC, KinjiKawaguchi commented on typing-app/src/components/molecules/LogoutButton.tsx
> +    router.push("/"); //リダイレクト
これは何のために置いてありますか

2024-03-27 02:20 UTC, KinjiKawaguchi commented on typing-app/src/components/molecules/GameStartButton.tsx
> +  };
この階層でこの関数を使わないなら LoginModalに移して良さそうです

2024-03-27 02:20 UTC, KinjiKawaguchi commented on typing-app/src/components/organism/HomeMenuContainer.tsx
> +    </Flex>
欲を言えばこの階層で、ログイン状態に応じて表示するボタンを変更したいが、今はこの導線で良しとしましょう。
いずれ改善したいのでIssueを立てておいてください。

2024-03-28 23:24 UTC, KikyoNanakusa commented on typing-app/src/components/molecules/GameStartButton.tsx
> +  };
移行しました

2024-03-28 23:25 UTC, KikyoNanakusa commented on typing-app/src/components/molecules/LogoutButton.tsx
> +    router.push("/"); //リダイレクト
何のためかわからなかったので削除

2024-03-28 23:25 UTC, KikyoNanakusa commented on typing-app/src/components/organism/HomeMenuContainer.tsx
> +    </Flex>
TODOコメントを追加

2024-03-29 05:24 UTC, KinjiKawaguchi approved these changes
LGTMしたいだけ

2024-03-29 05:24 UTC, h-takeyeah approved these changes
:sparkles:

2024-03-29 05:24 UTC, merged