chore: bun -> yarn
su-its/typing pull request #25
Opened 2024-03-26 04:32 UTC by KinjiKawaguchi

## やったこと

- bun -> yarn

2024-03-26 04:48 UTC, h-takeyeah reviewed
bun を yarn にしたときの手順、具体的にどんな作業を行ったかを記録のために取っておいてください。

あと、これは質問なのですが、emotionなどが依存関係に追加されたのはなぜですか(そもそも必要なの？っていうのと、PRの内容と違くない？っていう2つの意味で)

2024-03-26 04:48 UTC, h-takeyeah commented on typing-app/package.json
> +  "main": "src/app/page.tsx",
このフィールドはなくてもいいと思います！

2024-03-26 06:58 UTC, KinjiKawaguchi commented
以降の際にchakra周りで不具合が出ちゃったので、一旦chakraをすべて吹き飛ばしてドキュメント通り(今までは違った)インスコしたので付いてきた感じです

2024-03-26 07:11 UTC, h-takeyeah commented
なるほど

2024-03-26 07:24 UTC, h-takeyeah commented
手元に [4faf42e](https://github.com/su-its/typing/pull/25/commits/4faf42ee51f94e21f697f274cc9a4bbd417ca8f6) を pull してきて、node_modulesなどが残っている状態で yarn のバージョンを v4 に上げてみました。

前提として、4faf42e は以下の感じでした
- yarn.lock の先頭のあたりに `# yarn lockfile v1` と書かれている
- bun.lockb は削除されている

この状態で下記のコマンドを実行しました。

```
corepack enable
corepack prepare yarn@stable --activate
yarn -v # 4.1.1
yarn set version stable # ここで package.json に "packageManger" フィールドが書き込まれた
yarn install
```

特に最後の yarn install に関してはログに「マイグレートしてみるで」と出ていたので共有します

```
$ yarn install
➤ YN0087: Migrated your project to the latest Yarn version 🚀

➤ YN0000: · Yarn 4.1.1
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + @chakra-ui/react@npm:2.8.2, @emotion/react@npm:11.11.4, @emotion/styled@npm:11.11.0, and 593 more.
➤ YN0000: └ Completed in 12s 99ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 499 packages were added to the project (+ 294.09 MiB).
➤ YN0000: └ Completed in 14s 720ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 16s 58ms
➤ YN0000: · Done in 43s 99ms
```
このとき、yarn.lockが更新されました。v1の表記は消えています。
```plain
# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

(略)
```
また同時に新しく .yarnrc.yml が作成されました。このファイルは設定ファイルです。
```yaml
nodeLinker: node-modules
```
nodeLinker という設定は https://yarnpkg.com/features/linkers この文書が詳しいです。

2024-03-27 02:44 UTC, KinjiKawaguchi commented
バージョン指定と、その後yarnコマンドのログ

```
➜  typing-app git:(feat/front/bun-to-yarn-migration) ✗                      
corepack enable
corepack prepare yarn@stable
yarn set version stable
Preparing yarn@stable...
➤ YN0000: Downloading https://repo.yarnpkg.com/4.1.1/packages/yarnpkg-cli/bin/yarn.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-4.1.1.cjs
➤ YN0000: Done in 0s 88ms
➜  typing-app git:(feat/front/bun-to-yarn-migration) ✗ yarn
➤ YN0087: Migrated your project to the latest Yarn version 🚀

➤ YN0000: · Yarn 4.1.1
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + @chakra-ui/react@npm:2.8.2, @emotion/react@npm:11.11.4, @emotion/styled@npm:11.11.0, @radix-ui/react-slot@npm:1.0.2, and 592 more.
➤ YN0000: └ Completed in 2s 657ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 44 packages were added to the project (+ 8.15 MiB).
➤ YN0000: └ Completed in 0s 696ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 2s 890ms
➤ YN0000: · Done in 6s 308ms
➜  typing-app git:(feat/front/bun-to-yarn-migration) ✗ 
```

2024-03-27 05:04 UTC, h-takeyeah requested changes
ログ提出ありがとうございました

2024-03-27 13:17 UTC, h-takeyeah commented
コミット追加しました :t-rex:
- [update .gitignore for yaml](https://github.com/su-its/typing/pull/25/commits/d791b62281774e8799914323ebd9ede3b81d724d) yaml は yarn の誤字です :vomiting_face:
- [create .gitattributes recommended by yarn](https://github.com/su-its/typing/pull/25/commits/21c327cb6d81815d6bc6a5ed93783a81003a7452)
- [prevent users from using npm](https://github.com/su-its/typing/pull/25/commits/178f850912a6f1686e1fa1f3b768fdb714254f5c)
 npm install とかしようとすると "use yarn instead" と言われて落ちます。これで yarn を強制できるはずです(ただし npx コマンドはこの制限に引っかからず実行できる)

上の2つは yarnpkg 公式からの情報をもとにしていて、上はここ [which-files-should-be-gitignored](https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored) 、その下は同じページおよび create-next-app すると作成される .gitattributes がそれぞれソース :spaghetti: になります :memo:

2024-03-28 04:19 UTC, h-takeyeah commented on typing-app/.yarnrc.yml
7144384 で解決

2024-03-28 04:21 UTC, h-takeyeah submitted a review, later dismissed
LGTM!!! :+1: 😸

2024-03-28 04:27 UTC, h-takeyeah requested changes

2024-03-28 04:27 UTC, h-takeyeah commented on typing-app/docs/get-started.md
> +$ yarn
```suggestion
$ corepack enable
$ yarn
```

2024-03-28 04:41 UTC, h-takeyeah approved these changes
今度こそ

2024-03-28 04:47 UTC, merged