Feat/game screen/template （ゲーム画面途中まで）
su-its/typing pull request #27
Opened 2024-03-26 07:55 UTC by Tsuyopon-1067

**すごく重いPRですごめんなさい**

## やったこと

-   スタート画面からの画面遷移
-   ランダムに選ばれたテキストの表示
-   タイピングゲームのキー入力判定
-   瞬間的な入力速度の表示
-   残り時間の表示
-   残り時間が 0 になったときに POST リクエストを送信・画面遷移

## やらないこと

-   平均入力速度の表示（結果表示に必要）
-   残り時間が 0 になっていないときに文章を打ち終わったときのスコア送信・画面遷移

## できるようになること（ユーザ目線）

-   ゲーム開始 → ゲーム画面遷移，実際のプレイ（キー入力まで）

## できなくなること（ユーザ目線）

-   無し

## 動作確認

-   bun run build が通ることを確認．

```zsh
% bun run build
$ next build
   ▲ Next.js 14.1.0

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types
 ✓ Collecting page data
 ✓ Generating static pages (7/7)
 ✓ Collecting build traces
 ✓ Finalizing page optimization

Route (app)                              Size     First Load JS
┌ ○ /                                    389 B           254 kB
├ ○ /_not-found                          885 B          85.2 kB
├ ○ /game                                25.1 kB         155 kB
└ ○ /ranking                             389 B           254 kB
+ First Load JS shared by all            84.3 kB
  ├ chunks/69-5c6822682109e96b.js        28.9 kB
  ├ chunks/fd9d1056-780053702ed842a5.js  53.4 kB
  └ other shared chunks (total)          2.04 kB

○  (Static)  prerendered as static content
```

2024-03-26 08:05 UTC, h-takeyeah commented
CIが落ちてるのは私のせいなので気にしないでください

2024-03-26 08:15 UTC, h-takeyeah commented
@Tsuyopon-1067
本番環境へは Docker コンテナを持って行くつもりです(初めて言った)。なのでお手数ですが、docker でもうまく動くか確認をお願いします。

```
# ポート 3000 を使っている他のソフトがいたら終了しておく
cd typing-app
docker build -t su-its/typing-app:game-screen . # 最後のピリオドが大事
```
ビルドしたら起動してみて、ブラウザで思った通りの動作になっているかどうかを確認してください。
```
docker run --rm -p 3000:3000 su-its/typing-app:game-screen
```
Ctrl+Cで終了できます

2024-03-26 08:22 UTC, h-takeyeah commented on typing-app/src/components/pages/Game.tsx
> +    IDX_PRE,
について、自分で調べて直してみてください。この場合は Union Type とかがいいんじゃないかな
```ts
type ScreenIndex = "IDX_PRE" | "IDX_TYPING" | "IDX_RESULT"
```

2024-03-26 08:23 UTC, h-takeyeah commented on typing-app/src/components/pages/Game.tsx
> +    IDX_PRE,
subpageList が配列じゃなくてオブジェクトリテラルで書き直されれば enum でなくてもアクセスできるかな

2024-03-26 08:26 UTC, h-takeyeah commented on typing-app/src/components/templates/GameTyping.module.css
のちのちscssに移行するという予定ですか？それともこのままですか？

arkwくんがscssで書いてたのでその資源がもったいないかなーと思いまして

2024-03-26 08:44 UTC, h-takeyeah commented on typing-app/src/components/templates/GameTyping.tsx
> +import axios from "axios";
axios が依存関係にいないので CI が落ちてます。

ここ現在進行形で [`openapi-fetch`](https://github.com/drwpow/openapi-typescript/tree/main/packages/openapi-fetch)を使うか、使わないにしても window.fetch をラップした独自のクライアントを作ろうと考えてます。なので私の都合としては axios をやめてもらって fetch に変えてもらえると、依存が増えなくていいんですけど、axios便利だしね。どうしようねえ

2024-03-26 08:51 UTC, h-takeyeah requested changes
デカ PR お疲れさまでした！

CI が落ちてるのは axios がインストールされてないからなので、インストールすりゃ直ります。なぜ動作確認は行けたんだ？
ただ、OpenAPIからクライアントを自動生成しようとしているので、後々そっちを使うように修正してもらうかもしれません。(バックエンドとの通信に関係ないところでaxiosを使うなら、好きに使ってください)

enum は修正すべきだと思ったのでコメントしました。べきっていうのも変ですが、enumじゃないとできないことじゃないので使わない方がよいかなと思います。

2024-03-26 08:51 UTC, h-takeyeah commented on typing-app/src/types/RegisterScore.ts
> +  EndedAt: Date;
特に理由なければ小文字でお願いします。

```suggestion
  keystrokes: number;
  accuracy: number;
  score: number;
  startedAt: Date;
  sndedAt: Date;
```

2024-03-26 08:51 UTC, h-takeyeah commented on typing-app/docs/game-page.md
> +Game.tsx 内で`subPageList`配列に 3 つの `SubPage` コンポーネントを格納しておき，インデックスを変更することで画面を遷移させる．
(メモ)enum の変更をお願いしたので subPageList が配列じゃなくなるかもしれないし、そのままかもしれない。もし変わったらここもそのように修正する……。 📝

2024-03-27 09:20 UTC, Tsuyopon-1067 commented on typing-app/src/components/templates/GameTyping.module.css
こちらでscssがうまく動かせなかったので書き直しただけなので，npmに以降すればscssでも行けると思います．
ただUI変更の可能性もあるのでこのままのほうが（私が）対処しやすいかなって気持ちも．．

2024-03-27 10:06 UTC, Tsuyopon-1067 commented on typing-app/src/components/templates/GameTyping.tsx
> +import axios from "axios";
実装者と相談したところ，fetchに変える負担は大きくなさそうなので変更してもらえることになりました，

2024-03-27 12:54 UTC, h-takeyeah commented on typing-app/src/components/templates/GameTyping.module.css
なるほど、デザイナーは scss で書くのに慣れているけど、実装する側にしてみるとプレーンな CSS に近い module css の方がうまくいったという事例なのかな

その辺の属人化を防ぐのも今後の課題ですね(誰目線)。解決。

2024-03-31 03:22 UTC, h-takeyeah commented on typing-app/src/components/templates/GameTyping.tsx
> +    const typeTime = getTypingQueueListIndex(typingQueueList.length - 1) - getTypingQueueListIndex(0);
ここ typingQueueList を参照しなくなってる気がするんですが、変更前と動作変わっちゃわないですかね

2024-03-31 09:02 UTC, h-takeyeah requested changes

2024-03-31 12:08 UTC, Tsuyopon-1067 commented on typing-app/src/components/templates/GameTyping.tsx
> +    const typeTime = getTypingQueueListIndex(typingQueueList.length - 1) - getTypingQueueListIndex(0);
ここは関数getTypingQueueListIndex内でtypingQueueListを参照しているので問題なしのはずです（ゲーム中にちゃんと速度出るし）

2024-03-31 13:31 UTC, h-takeyeah commented on typing-app/src/components/templates/GameTyping.tsx
> +    const timeFromStart = new Date().valueOf() - startedAt.valueOf();
超厳密にいうとDate.nowの方がDateオブジェクト作らない分だけコスト低い

valueOf は getTime と等価であるとはいえ内部的に呼ばれるものなので getTime がベター

ロジック自体はパーフェクトです！

2024-03-31 13:31 UTC, h-takeyeah commented on typing-app/src/components/templates/GameTyping.tsx
> +  const [typingQueueList] = useState([] as number[]);
```suggestion
  const [typingQueueList] = useState<number>([]);
```

2024-03-31 13:31 UTC, h-takeyeah commented on typing-app/docs/game-page-wpm-logarithm.md
@Tsuyopon-1067 
`を満たす$f$を作る`のところとかTeXソースがそのまま表示されちゃってたんですけど、環境によって表示されたりされなかったりして一概にソースが原因とも言えないのでこのPRではスルーします。空白入れたら直るんですが。でももし気づいたらこのPRの後で直してくださいな～

2024-03-31 13:31 UTC, h-takeyeah commented on typing-app/src/components/templates/GameTyping.tsx
> +      .then(() => {})
```suggestion

```

2024-03-31 13:38 UTC, h-takeyeah commented on typing-app/src/components/templates/GameTyping.tsx
> +    } as ResultScore);
as は必要ないのでここでは単に分かりやすさのために使っていると推測します
```suggestion
    });
```
型が分かりやすいとは思うけれど、その目的であれば冗長だけど as を使わず `const resultScore: ResultScore = {...}` と書くべきだと思います。as を使うとコンパイラを黙らせるためにやむを得ず使っている、という印象を受けます

2024-03-31 13:38 UTC, h-takeyeah commented on typing-app/src/components/templates/GameTyping.tsx
> +    } as RegisterScore;
```suggestion
    const registeredScore: RegisterScore = {
      keystrokes: correctType,
      accuracy: accuracy,
      score: (correctType / typeTimeSeconds) * 60,
      startedAt: startedAt,
      endedAt: endedAt,
    };
```

2024-03-31 13:40 UTC, h-takeyeah commented on typing-app/src/components/templates/GameTyping.tsx
> +import RegisterScore, { ResultScore } from "@/types/RegisterScore";
ResultScoreは使ってないから消してもよいっぽい？

2024-03-31 13:45 UTC, h-takeyeah commented on typing-app/src/components/templates/GameTyping.tsx
> +      .then(() => {})
POST結果を使わないのであれば
```suggestion
```

2024-04-01 05:37 UTC, h-takeyeah commented on typing-app/docs/game-page-wpm-logarithm.md
> +以下の値似合わせてゲージのラベルを更新する必要がある．
修正済み

2024-04-01 05:38 UTC, h-takeyeah commented on typing-app/src/components/templates/GameTyping.tsx
> +  }, [count, nextPage, userId]); // ビルド時の警告防止のためにuserIdも依存リストに追加
対応済み

2024-04-01 05:38 UTC, h-takeyeah commented on typing-app/src/components/templates/GameTyping.tsx
> +  }, [nextPage, userId, typeIndex]); // ビルド時の警告防止のためにuserIdも依存リストに追加
対応済み

2024-04-01 05:38 UTC, h-takeyeah commented on typing-app/src/components/templates/GameTyping.tsx
> +import axios from "axios";
対応済み

2024-04-01 05:38 UTC, h-takeyeah commented on typing-app/src/components/pages/Game.tsx
> +    IDX_PRE,
対応済み

2024-04-01 05:42 UTC, h-takeyeah commented on typing-app/src/components/templates/GameResult.tsx
> +}
案Bで対応！ :pray:

2024-04-01 05:47 UTC, h-takeyeah commented on typing-app/src/components/templates/GameTyping.tsx
> +import RegisterScore, { ResultScore } from "@/types/RegisterScore";
使っていたらしい。私の指摘が間違っていたので取り消します。すみませんでした :bow:

2024-04-01 06:14 UTC, h-takeyeah commented on typing-app/docs/game-page-wpm-logarithm.md
@Tsuyopon-1067  これは今やらないことにした

2024-04-01 06:18 UTC, h-takeyeah commented on typing-app/src/components/templates/GameTyping.tsx
> +    const timeFromStart = new Date().valueOf() - startedAt.valueOf();
動かないわけじゃないので対応しないことにした。指摘を取り消します。

2024-04-01 06:19 UTC, h-takeyeah commented on typing-app/src/components/templates/GameTyping.tsx
> +    } as ResultScore);
直した

2024-04-01 06:19 UTC, h-takeyeah commented on typing-app/src/components/templates/GameTyping.tsx
> +    } as RegisterScore;
直した

2024-04-01 06:24 UTC, h-takeyeah approved these changes
:+1 :100:

2024-04-01 06:27 UTC, KinjiKawaguchi approved these changes
![LGTM](https://images.lgtmgen.org/36f9308d-d3aa-422f-a4e8-b1a58e593704)

2024-04-01 06:29 UTC, h-takeyeah commented on typing-app/docs/game-page.md
> +Game.tsx 内で`subPageList`配列に 3 つの `SubPage` コンポーネントを格納しておき，インデックスを変更することで画面を遷移させる．
@Tsuyopon-1067  #52 などで対応していくことにしたので今やりません！

2024-04-01 06:31 UTC, merged