Feat/frontend/project-foundation
su-its/typing pull request #5
Opened 2024-03-01 10:06 UTC by KinjiKawaguchi

- nextのプロジェクト作成
- ディレクトリ戦略の作成
- shacnのインストール

2024-03-02 06:30 UTC, h-takeyeah requested changes
おつです。
EOLのところと、勘違いだったらいいんですけど`use client`本当に要らない？ってのの2点はマストで確認してほしいです。

2024-03-02 06:30 UTC, h-takeyeah commented on typing-app/docs/directory-strategy.md
> +
昔ながらのpages router ではなく app router を使う旨をここへ明記しておいてください。それらを区別できていた方が調べ物がしやすいと思うので。

2024-03-02 06:30 UTC, h-takeyeah commented on typing-app/src/components/molecule/toast/toast.tsx
> +import * as React from "react";
`"use client";`忘れ？

2024-03-02 06:30 UTC, h-takeyeah commented on typing-app/src/components/atoms/button/button.tsx
> +import * as React from "react";
`"use client";`忘れ？
でも動いてるからいいのかしら？
すみません、よく分からないので心配になりました。大丈夫そうならご放念くださいませ:bow:

2024-03-02 06:30 UTC, h-takeyeah commented on typing-app/src/components/molecule/toast/use-toast.ts
> +// Inspired by react-hot-toast library
個人的には使うときになったらcommitに乗せればいい派です。すぐ使う予定がありますか？それとも単にmoleculeディレクトリを用意するために？

2024-03-02 06:30 UTC, h-takeyeah commented on typing-app/src/types/user.ts
userは必要になる見通しがあるのですかね？あるから置いてあると思うのだけれど、とりあえずuser.tsという名前でおいてあるだけだったら無い方がよいです。

2024-03-02 06:30 UTC, h-takeyeah commented on typing-app/tailwind.config.ts
NOEOLなのでファイル末尾に改行を入れるか、ファイル末尾で改行してからバックスペースで消すかしてください(@arkwnet あってる？)。

2024-03-02 06:31 UTC, h-takeyeah commented
@KinjiKawaguchi バックエンドのAPIとはどうやって結合する予定ですか？まったく白紙？

2024-03-02 06:32 UTC, KinjiKawaguchi commented on typing-app/src/components/molecule/toast/toast.tsx
> +import * as React from "react";
"use client"ってどこでつけるのが適切なんですかね
use clientをつけるべきページのルートでつけたりしていました

2024-03-02 06:32 UTC, KinjiKawaguchi commented on typing-app/src/components/molecule/toast/use-toast.ts
> +// Inspired by react-hot-toast library
後者ですね

2024-03-02 06:33 UTC, KinjiKawaguchi commented on typing-app/src/types/user.ts
こちらも後者

2024-03-02 06:38 UTC, h-takeyeah commented on typing-app/src/components/molecule/toast/toast.tsx
> +import * as React from "react";
ふええ…。React.useStateとかReact.useEffectなどはServer Componentsでの使用ができないので、それらを使う場合はつけると思ってるけど違うのかな。https://ja.react.dev/reference/react/use-client#when-to-use-use-client

2024-03-02 06:39 UTC, h-takeyeah commented on typing-app/src/components/molecule/toast/use-toast.ts
> +// Inspired by react-hot-toast library
うーんじゃあ無い方がよいと思います。必要になったら乗せれば。

2024-03-02 06:40 UTC, h-takeyeah commented on typing-app/src/types/user.ts
同じく消した方がよいと思います。ディレクトリ作るならってのはもう文書としてdocs/に書いたのだから必要になったら乗せれると思います。

2024-03-02 06:42 UTC, KinjiKawaguchi commented
@h-takeyeah 
なんだかんだRESTを真面目にやったことが無いので白紙でぃす

2024-03-02 06:42 UTC, KinjiKawaguchi commented on typing-app/src/components/molecule/toast/toast.tsx
> +import * as React from "react";
や、あってます。
フックを使う時ファイルには全部書く運用でいいのかな

2024-03-02 06:48 UTC, h-takeyeah commented on typing-app/src/components/molecule/toast/toast.tsx
> +import * as React from "react";
まあエラー出なければヨシ！(つーかテストコードを書け)

2024-03-02 06:49 UTC, h-takeyeah commented on typing-app/src/components/molecule/toast/toast.tsx
> +import * as React from "react";
toast使ってないからエラーになるかどうかわかんないじゃん！！(ﾑｷｰ

2024-03-02 06:51 UTC, h-takeyeah commented
> @h-takeyeah なんだかんだRESTを真面目にやったことが無いので白紙でぃす

ではそこは自分が巻き取るので、このPRでは追究しないことにしますね、ありがとう。

2024-03-05 04:25 UTC, h-takeyeah commented
今気づいたのですが package-lock.json と bun.lockb が両方あるのはまずい(\*)のでどちらか一方を残してください。

- bun に乗るなら -> `git rm package-lock.json`
- bun をやめて npm を使うなら -> `git rm bun.lockb`

(\*)後からこのプロジェクトを見返したときにパッケージマネージャどっちなの？と混乱する可能性があるという点でまずい。動かなくはないです。

2024-03-05 04:26 UTC, KinjiKawaguchi commented
ホントですね、途中からそうだBUNにしようと思い立ったもので...申し訳ないです。

できれば今日中に終わらせます

2024-03-05 06:12 UTC, h-takeyeah commented on typing-app/src/components/molecule/toast/toast.tsx
> +import * as React from "react";
言葉足らずですみません、「テストコードを書け」というのは理想的にはそうですが、「本当はテストコードを書いてちゃんと動くか確かめてからコミットするべきだが今のところエラーになってないならそのままでいい」の意です。
なのでこのPRでテストコード書かなくてよいです。

2024-03-06 09:42 UTC, h-takeyeah approved these changes
手元でも動作確認できました。コメントの箇所も対応お疲れさまでした！

LGTM:+1:

2024-03-06 11:41 UTC, merged