Style/frontend/pre game
su-its/typing pull request #55
Opened 2024-04-01 15:05 UTC by Shibatch28

## やったこと

- ゲーム開始前の画面を追加した

## やらないこと

- 説明の内容

## できるようになること（ユーザ目線）

- 説明画面が追加された

## できなくなること（ユーザ目線）

- 特になし

## 動作確認

- `yarn build`が通ることを確認

## その他

- レイアウトの確認をお願いします

2024-04-02 12:19 UTC, KinjiKawaguchi reviewed
@Shibatch28 
該当ページのスクリーンショットをTicketに貼っていただけるとレビューしやすいかもです！

2024-04-02 12:38 UTC, Shibatch28 commented
貼りました！

https://github.com/su-its/typing/issues/56#issuecomment-2031932730

2024-04-03 02:36 UTC, KinjiKawaguchi reviewed
![image](https://github.com/su-its/typing/assets/93261102/91792646-ac99-4a3d-8c83-1dac6079202b)

2024-04-03 02:36 UTC, KinjiKawaguchi commented
@Shibatch28 TicketじゃなくてPRでしたTT

2024-04-03 02:44 UTC, KinjiKawaguchi commented
@Shibatch28 @Tsuyopon-1067 @h-takeyeah 
説明に何を表示するのかなども詰めて、完成してからMergeしたいです！

2024-04-03 02:46 UTC, KinjiKawaguchi reviewed
@h-takeyeah @Shibatch28 @Tsuyopon-1067 
説明に何を表示するのかなど、Pre Gameとしてリリースして大丈夫な状態でMergeしたいです！

2024-04-03 10:28 UTC, KinjiKawaguchi requested changes
@Shibatch28 Rereviewのタイミングで改めてこのPRにスクショをいただけると嬉しいです！

2024-04-03 11:16 UTC, Shibatch28 commented
現状
![image](https://github.com/su-its/typing/assets/119596854/775c358e-c83b-409e-92eb-2562b44a5f8f)

2024-04-04 04:27 UTC, h-takeyeah commented
説明(のページ)に何を表示するのか、について私はフォーカスが外れたときは枠？をクリックすれば戻れる旨を追加したほうがいいと思う

2024-04-04 05:43 UTC, Shibatch28 commented
![image](https://github.com/su-its/typing/assets/119596854/7233f40e-44c4-4d4f-9462-0808b13e64ba)

2024-04-04 06:42 UTC, h-takeyeah approved these changes
:+1: フォーカスが外れたときの対処方法が記載されたことを確認しました。お疲れ様でした。

> @h-takeyeah @Shibatch28 @Tsuyopon-1067 説明に何を表示するのかなど、Pre Gameとしてリリースして大丈夫な状態でMergeしたいです！

がまだ解決されていませんが、自分としては指摘した部分が直ったので :heavy_check_mark:

2024-04-04 07:04 UTC, KinjiKawaguchi approved these changes
同上です。
ただtemplates/GamePre.tsxはアトミックデザイン的に問題があるので、いずれ直します。

2024-04-04 07:08 UTC, merged