feat: リザルト画面で「ゲームを終了する」ボタンの追加
su-its/typing pull request #80
Opened 2024-04-04 07:32 UTC by waka-eup25

## やったこと

- リザルト画面において，「次へ」ボタンを「もう一度プレイする」ボタンに名前を変更
- 「ゲームを終了する」ボタンを追加した

## やらないこと

- 無し

## できるようになること（ユーザ目線）

- リザルト画面において，「ゲームを終了する」ボタンか「もう一度プレイする」ボタンかどちらかを選択することができる

## できなくなること（ユーザ目線）

- 無し

## 動作確認

- yarn buildが通ることを確認
```
yarn build
   ▲ Next.js 14.1.0
   - Environments: .env

   Creating an optimized production build ...
 ⚠ For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'npm i sharp', and Next.js will use it automatically for Image Optimization.
Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
Compiler server unexpectedly exited with code: null and signal: SIGTERM
 ⚠ For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'npm i sharp', and Next.js will use it automatically for Image Optimization.
Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
Compiler client unexpectedly exited with code: null and signal: SIGTERM
 ✓ Compiled successfully
 ✓ Linting and checking validity of types
 ✓ Collecting page data
 ✓ Generating static pages (7/7)
 ✓ Collecting build traces
 ✓ Finalizing page optimization

Route (app)                              Size     First Load JS
┌ ○ /                                    1.55 kB         258 kB
├ ○ /_not-found                          882 B          85.2 kB
├ ○ /game                                9.37 kB         139 kB
└ ○ /ranking                             1.68 kB         137 kB
+ First Load JS shared by all            84.3 kB
  ├ chunks/69-684208d8427a30a4.js        28.9 kB
  ├ chunks/fd9d1056-780053702ed842a5.js  53.4 kB
  └ other shared chunks (total)          2.04 kB

○  (Static)  prerendered as static content
```

2024-04-04 07:33 UTC, KinjiKawaguchi requested changes
@waka-eup25 画面のスクリーンショットがPRにあると嬉しいです！

2024-04-04 07:39 UTC, waka-eup25 commented
リザルト画面のスクリーンショットです！これで大丈夫でしょうか
![result-screen](https://github.com/su-its/typing/assets/100208180/e514a51e-c162-4a6f-86a6-8e00cbb4ef40)

2024-04-04 07:53 UTC, KinjiKawaguchi requested changes
@waka-eup25 
スクリーンショット、迅速な対応をありがとうございます。

プログラムで一点気になるところがあったので、コメントしておきました。

2024-04-04 07:53 UTC, KinjiKawaguchi commented on typing-app/src/components/templates/GameResult.tsx
> +          <Button onClick={nextPage} colorScheme="red" size="lg" w="80%" h="90%">
同じメソッドを叩いて良いのか?

2024-04-04 07:53 UTC, KinjiKawaguchi commented on typing-app/src/components/templates/GameResult.tsx
> +          <Button onClick={nextPage} colorScheme="blue" size="lg" w="80%" h="90%">
ここと上

2024-04-04 08:22 UTC, waka-eup25 commented on typing-app/src/components/templates/GameResult.tsx
> +          <Button onClick={nextPage} colorScheme="blue" size="lg" w="80%" h="90%">
すみませんコピペしたらonClickの中身を変更するのを失念していました．
「ゲームを終了する」ボタンの方はHomeに遷移するという解釈で合っていますか？

2024-04-04 09:03 UTC, KinjiKawaguchi commented on typing-app/src/components/templates/GameResult.tsx
> +          <Button onClick={nextPage} colorScheme="blue" size="lg" w="80%" h="90%">
あってます！

2024-04-04 15:59 UTC, KinjiKawaguchi requested changes
フォーマットで怒られてCi失敗しているので、フォーマッタを掛けてPushし直していただければ、Approveできます！

2024-04-04 20:36 UTC, KinjiKawaguchi requested changes

2024-04-04 20:36 UTC, KinjiKawaguchi commented on typing-app/src/components/templates/GameResult.tsx
> +          <Button onClick={() => window.location.href = '/'} colorScheme="red" size="lg" w="80%" h="90%">
Next.jsのベストプラクティスに従いたいので、遷移方法について指摘させてください。

まず
```typescript
import { useRouter } from "next/navigation";
```
でuseRouterフックをインポートします。

その後
routerオブジェクトを取得し、onClickのイベントハンドラを定義
```typescript
const router = useRouter();

const pushToRoot = () => {
  router.push("/");
}
```


```suggestion
<Button onClick={pushToRoot} colorScheme="red" size="lg" w="80%" h="90%">
  ゲームを終了する
</Button>
```

2024-04-05 20:47 UTC, KinjiKawaguchi approved these changes
LGTM

2024-04-05 20:48 UTC, merged