Feat/ranking
su-its/typing pull request #94
Opened 2024-04-05 12:37 UTC by araaki12345

## チケットへのリンク
#74

## やったこと

- APIから実データを取得し、ランキングとして表示する機能を実装

## やらないこと

- データの最大数をAPIから取ってくること
自分の順位を視覚的に表示させる機能(API待ち)を実装する際に一緒に実装します。

## できるようになること（ユーザ目線）

- ランキングを正打率と入力文字数の2つの項目で閲覧することができる

## できなくなること（ユーザ目線）

- 特に無し

## 動作確認

- ブラウザ上でタブやぺージの更新ボタン、変更ボタンの動作を確認しました

## その他

2024-04-05 19:25 UTC, KinjiKawaguchi approved these changes
LGTM(取り消し)

2024-04-05 20:21 UTC, KinjiKawaguchi requested changes
APIの変更完了に伴い、maximum変数の設定も本PRでやってしまいましょう。

2024-04-06 06:13 UTC, h-takeyeah commented
CIが落ちてるのは私が解決策を模索して気づいた時点で連絡しますので、いったん気にしないでください。なるべく早くやります

2024-04-06 08:42 UTC, h-takeyeah commented
なんか知らんけどCI通った笑

2024-04-06 16:15 UTC, h-takeyeah approved these changes

2024-04-06 16:16 UTC, KinjiKawaguchi approved these changes
LGTM
ほんとにお疲れさまでした

2024-04-06 16:16 UTC, merged