Feat/backend/api/v1
su-its/typing pull request #99
Opened 2024-04-06 07:55 UTC by shin0729

## チケットへのリンク

- 

## やったこと

- ユーザーのカレントランキング返す機能を実装
- 最大スコア(accracy,keystroke切り替え可)から自分より上のユーザーを数えて自分の順位を返します

## やらないこと

- とくになし

## できるようになること（ユーザ目線）

- 何ができるようになるのか？（あれば。無いなら「無し」で OK）

## できなくなること（ユーザ目線）

- 何ができなくなるのか？（あれば。無いなら「無し」で OK）

## 動作確認

- 動作確認してないので自分でデモデータ作ってこのあとやります

## その他

- レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）

2024-04-06 08:23 UTC, KinjiKawaguchi requested changes

2024-04-06 08:23 UTC, KinjiKawaguchi commented on typing-server/api/handler/user.go
> +}
scoreリソースなのにUser.goで実装していいの?

2024-04-06 08:23 UTC, KinjiKawaguchi commented on typing-server/api/repository/user.go
> +			First(ctx)
それぞれのスコアにソレがユーザーにとって最大かどうかを示すフラグがあるよ
Schemaを見てみて

あとcaseの中身も冗長だね
scoreRanking返すメソッドを参考にすれば上手にかけるよ

2024-04-06 08:23 UTC, KinjiKawaguchi commented on typing-server/api/router/router.go
> +	r.Get("/scores/{user-id}/current-rank", handler.GetMyScoreRanking)
current-rank
current_rankどっちがベストプラクティスかしらべて

2024-04-06 08:24 UTC, KinjiKawaguchi requested changes

2024-04-06 08:24 UTC, KinjiKawaguchi commented on typing-server/api/service/user.go
> +func GetMyScoreRanking(ctx context.Context, client *ent.Client, userID uuid.UUID, sortBy string) (int, error) {
このディレクトリでやるべきことか検討して

https://github.com/su-its/typing/blob/develop/typing-server/docs/directory-strategy.md?plain=1

2024-04-06 08:25 UTC, shin0729 commented on typing-server/api/handler/user.go
> +}
確かに過ぎる．勝手にuser直下だと思ってた．ドキュメントもscoreだ

2024-04-06 08:26 UTC, shin0729 commented on typing-server/api/router/router.go
> +	r.Get("/scores/{user-id}/current-rank", handler.GetMyScoreRanking)
apiのパス( /scores/{user-id}/current-rank:)はハイフンがベストです

2024-04-06 09:22 UTC, shin0729 commented on typing-server/api/service/user.go
> +func GetMyScoreRanking(ctx context.Context, client *ent.Client, userID uuid.UUID, sortBy string) (int, error) {
ビジネスロジックではあると思うし，repoでもhandlerでもないからここかなぁとい思うのだけれど

2024-04-06 15:02 UTC, KinjiKawaguchi requested changes
前から思っていたが、カプセル化の使い方が間違っているので、調べてなにが適切なだと思うか考えて

2024-04-06 15:02 UTC, KinjiKawaguchi commented on typing-server/api/service/score.go
> +	}
ここも冗長

service層からDBの操作をしているけど大丈夫ですか

2024-04-08 11:22 UTC, shin0729 commented on typing-server/api/repository/score.go
> +	maxScore, err := query.First(ctx)
カプセル化はデータを外部から変更できないようにメソッドとかの中にしまい込む(privateにするとかもそう)やつで僕が言ってたのはモジュール化でした．感謝

2024-04-08 11:23 UTC, shin0729 commented on typing-server/api/service/score.go
> +	}
service層はビジネスロジックを扱うのでDBの操作をするのはrepository層に委譲すべき．感謝

2025-02-14 17:16 UTC, closed without merging